### ISSUE TITLE
Problems opening the .exe

### ISSUE THREAD

**Issue by NeoHowls** [lehieugch68/PJ5-FMSG-Extractor#2]
Good morning, I have been trying to use the application PJ5-FMSG-Extractor.exe
in all possible ways.
from dragging the fmsg file, opening it as administrator etc. etc.

if it can cause problems I have Window 11, 8GB ram and I5 10gen

-

**Comment by lehieugch68** [comment]
It's a command line tool, here's Google's guide to using them:

> 1. Go to the Windows command prompt. One option is to choose Run from the Windows Start menu, type cmd, and click OK.
> 2. Use the "cd" command to change to the folder containing the program you wish to run.
> 3. Run the command line program by typing its name and pressing Enter.

In this case, open cmd in the folder containing PJ5-FMSG-Extractor.exe and type:
```
//Extract
PJ5-FMSG-Extractor.exe -e digital_artbook.fmsg digital_artbook.fmsg.txt //for file
PJ5-FMSG-Extractor.exe -e USen USen-extracted //for folder

//Import
PJ5-FMSG-Extractor.exe -i digital_artbook.fmsg digital_artbook.fmsg.txt digital_artbook.fmsg.new //for file
PJ5-FMSG-Extractor.exe -i USen USen-extracted USen-new //for folder
```
